### ISSUE TITLE
i.getAttribute is not a function at e3.onwheel

### ISSUE THREAD

**Issue by UTing1119** [zqy233/svg-zoom-drag-vue-directives#1]
I'm using axios to get svg string and pass it through props.

component1.vue
```javascript
<template>
  <svgHandler :svgString="svg_string" />
</template>

<script setup>
import svg from "./test.svg"
import axios from 'axios'

var svg_string = ref("")

onMounted(()=>{
  axios.get(svg).then(res=>{
    console.log(res)
    svg_string.value = res.data
  })
})

</script>
```

svgHandler.vue

```javascript
<template>
  <div id="svg" v-html="svgString" v-svgWheel v-svgDrag></div>
</template>

<script setup>
const props = defineProps({
  svgString:{
    type: String,
    default: '',
  },
})
</script>
```

and got this error:
![image](https://github.com/zqy233/svg-zoom-drag-vue-directives/assets/74576629/ebb27269-5f95-468c-b52b-e58924f5f608)

how can I fix it? or get svg string in other way?

---
edit:
I'm using Vue3 , TypeScript ,Vite

**Comment by zqy233** [comment]
I think there is a problem with the svg  string, v-html is not generating an svg element correctly, can you provide a repository containing a simple svg string file

**Comment by UTing1119** [comment]
my page show correctly svg and I can get item by id or so.
everything work except this.

I'll provide a repository asap since codesandbox and codepen cannot find this lib.

**Comment by UTing1119** [comment]
I found the reason.
Cuz my svg have other label like this:
```
<?xml version="1.0" encoding="UTF-16"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg>...</svg>
```

those label is automatically created by drawing software.
if you don't remove those label, it can show up correctly but cannot be zoom in/out or drag.

and this doesn't work too:

```
<div v-svgWheel v-svgDrag>
  <div id="svg" v-html="svgString"></div>
</div>
```

**Comment by zqy233** [comment]
OK, you can use JavaScript to extract the SVG part.
```js
const svgString = fullSvgString.replace(/<\?xml.*\?>\s*<!DOCTYPE[^>]*>/, '');
```
